<center>
<img src="../../img/ods_stickers.jpg">
## Открытый курс по машинному обучению
<center>
Автор материала: Юрий Кашницкий, программист-исследователь Mail.Ru Group <br> 

Материал распространяется на условиях лицензии [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Можно использовать в любых целях (редактировать, поправлять и брать за основу), кроме коммерческих, но с обязательным упоминанием автора материала.

# <center>Домашнє завдання № 1 (демо).<br> Аналіз даних доходів населення UCI Adult</center>

**В завданні пропонується за допомогою Pandas дати відповідь на кілька запитань по даним репозиторія UCI [Adult](https://archive.ics.uci.edu/ml/datasets/Adult).**

Унікальні значення ознак:
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

In [35]:
import pandas as pd
from black.comments import make_comment

In [36]:
data = pd.read_csv('adult.data.csv')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Скільки чоловіків и жінок (ознака *sex*) представлено в цьому наборі даних?**

In [37]:
male_count = (data["sex"] == "Male").sum()
print(f"Male count: {male_count}")
female_count = (data["sex"] == "Female").sum()
print(f"Female count: {female_count}")

Male count: 21790
Female count: 10771

**2. Який середній вік (ознака *age*) жінок?**

In [38]:
mean_age = data.loc[data["sex"] == "Female", "age"].mean()
print(f"Female mean age: {mean_age}")

Female mean age: 36.85823043357163

**3. Яка доля громадян Німеччини (ознака *native-country*)?**

In [39]:
german_citizens_ratio = (data["native-country"] == "Germany").mean()
print(f"German citizens ratio: {german_citizens_ratio}")

German citizens ratio: 0.004207487485028101

**4-5. Які средні значення та средньоквадратичні відхилення віку тих, хто отримує більше 50K на рік (ознака *salary*) і тих, хто отримує менше 50K на рік?**

In [40]:
gt_50k_age = data.loc[data["salary"] == ">50K", "age"]
gt_50k_age.mean()
print(f"Mean of age for people with a salary >50K: {gt_50k_age.mean()}")
gt_50k_age.std()
print(f"Std of age for people with a salary >50K: {gt_50k_age.std()}")
lte_50k_age = data.loc[data["salary"] == "<=50K", "age"]
lte_50k_age.mean()
print(f"Mean of age for people with a salary <=50K: {lte_50k_age.mean()}")
lte_50k_age.std()
print(f"Std of age for people with a salary <=50K: {lte_50k_age.std()}")

Mean of age for people with a salary >50K: 44.24984058155847
Std of age for people with a salary >50K: 10.519027719851826
Mean of age for people with a salary <=50K: 36.78373786407767
Std of age for people with a salary <=50K: 14.02008849082488

**6. Чи правда, що люди, які отримують більше 50k, мають як мінімум вищу освіту? (ознака *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [41]:
allowed = ["Bachelors", "Prof-school", "Assoc-acdm", "Assoc-voc", "Masters", "Doctorate"]
all_have = data.loc[data["salary"] == ">50K", "education"].isin(allowed).all()
print(
    'All people with a salary >50K have higher education'
    if all_have
    else 'Not all people with a salary >50K have higher education'
)

Not all people with a salary >50K have higher education

**7. Порахуйте статистику віку для кожної раси (ознака *race*) і кожної статі. Використайте *groupby* и *describe*. Знайдіть таким сином максимальний вік чоловіків раси *Amer-Indian-Eskimo*.**

In [42]:
aie_max_age = data.groupby("race")["age"].describe().loc["Amer-Indian-Eskimo", "max"]
print(f"Max age of Amer-Indian-Eskimo: {aie_max_age}")

Max age of Amer-Indian-Eskimo: 82.0

**8. Серед кого більша доля багатіших (>50K): серед одружених чи не одружених чоловіків (ознака *marital-status*)? За одружених вважаємо тих, у кого *marital-status* починається із *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), всі інші - не одружені.**

In [43]:
men = data[data["sex"] == "Male"]
married_mask = men["marital-status"].str.startswith("Married")
married_men = men[married_mask]
unmarried_men = men[~married_mask]
married_men_gt_50k_ratio = (married_men["salary"] == ">50K").mean()
print(f"Married men earn >50K ratio: {married_men_gt_50k_ratio}")
unmarried_men_gt_50k_ratio = (unmarried_men["salary"] == ">50K").mean()
print(f"Unmarried men earn >50K ratio: {unmarried_men_gt_50k_ratio}")
print(
    'Ratio of married men who earn >50K is bigger than unmarried'
    if married_men_gt_50k_ratio > unmarried_men_gt_50k_ratio
    else 'Ratio of unmarried men who earn >50K is bigger than married'
)

Married men earn >50K ratio: 0.4405139945351156
Unmarried men earn >50K ratio: 0.08449509031397745
Ratio of married men who earn >50K is bigger than unmarried

**9. Яку максимальну кількість годин в тиждень працює людина (ознака *hours-per-week*)? Скільки людей працюють таку кількість годин і який відсоток серед них багатих?**

In [44]:
max_work_hours = data["hours-per-week"].max()
print(f"Max work hours: {max_work_hours}")
hardworking_people = data[data["hours-per-week"] == max_work_hours]
hardworking_people_count = hardworking_people.shape[0]
print(f"Hardworking people count: {hardworking_people_count}")
rich_people_percent = (hardworking_people["salary"] == ">50K").mean() * 100
print(f"Percent of rich people: {rich_people_ratio}")

Max work hours: 99
Hardworking people count: 85
Percent of rich people: 29.411764705882355

**10. Порахуйте середню тривалість роботи на тиждень (*hours-per-week*) серед багатих і бідних (*salary*) для кожної країни (*native-country*).**

In [45]:
data.groupby(["native-country", "salary"])["hours-per-week"].mean().unstack()

salary                          <=50K       >50K
native-country
?                           40.164760  45.547945
Cambodia                    41.416667  40.000000
Canada                      37.914634  45.641026
China                       37.381818  38.900000
Columbia                    38.684211  50.000000
Cuba                        37.985714  42.440000
Dominican-Republic          42.338235  47.000000
Ecuador                     38.041667  48.750000
El-Salvador                 36.030928  45.000000
England                     40.483333  44.533333
France                      41.058824  50.750000
Germany                     39.139785  44.977273
Greece                      41.809524  50.625000
Guatemala                   39.360656  36.666667
Haiti                       36.325000  42.750000
Holand-Netherlands          40.000000        NaN
Honduras                    34.333333  60.000000
Hong                        39.142857  45.000000
Hungary                     31.300000  50.000000
India                       38.233333  46.475000
Iran                        41.440000  47.500000
Ireland                     40.947368  48.000000
Italy                       39.625000  45.400000
Jamaica                     38.239437  41.100000
Japan                       41.000000  47.958333
Laos                        40.375000  40.000000
Mexico                      40.003279  46.575758
Nicaragua                   36.093750  37.500000
Outlying-US(Guam-USVI-etc)  41.857143        NaN
Peru                        35.068966  40.000000
Philippines                 38.065693  43.032787
Poland                      38.166667  39.000000
Portugal                    41.939394  41.500000
Puerto-Rico                 38.470588  39.416667
Scotland                    39.444444  46.666667
South                       40.156250  51.437500
Taiwan                      33.774194  46.800000
Thailand                    42.866667  58.333333
Trinadad&Tobago             37.058824  40.000000
United-States               38.799127  45.505369
Vietnam                     37.193548  39.200000
Yugoslavia                  41.600000  49.500000